# Generated by Django 5.1.6 on 2025-02-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/ingredientes/'),
        ),
        migrations.AddField(
            model_name='platillo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/platillos/'),
        ),
    ]
