# Generated by Django 5.1.6 on 2025-02-20 01:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0002_ingrediente_imagen_platillo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platilloingrediente',
            name='ingrediente',
        ),
        migrations.RemoveField(
            model_name='platilloingrediente',
            name='platillo',
        ),
        migrations.AddField(
            model_name='platillo',
            name='ingredientes',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='descripcion',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sushi.usuario'),
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.DeleteModel(
            name='PlatilloIngrediente',
        ),
    ]
